### ISSUE TITLE
Don't require a ViewCell to specify a layoutId

### ISSUE THREAD

**Issue by georgeantonious** [gantonious/ViewCellAdapter#58]
We may not want to always directly inflate a resource file. This can make view generation too restrictive.

**Comment by gantonious** [comment]
To do this we can split up `ViewHolder` creation to a series of pipelined steps. 

First we can define a `createView()` method that just creates a view. With the following default implementation. This way it can be overridden to facilitate view construction that does not directly inflate a layout. We can leave a base `getLayoutId()` method that returns `-1` so users are not forced to define a layout.

```java
public View createView(ViewGroup parent) {
    return inflate(parent, getLayoutId());
}
```

Then we can add a `createViewHolder(View view)` method that takes in the generated view and constructs the expected ViewHolder. We can default to reflection based construction here.

```java
public TViewHolder createViewHolder(View view) {
    try {
        Constructor<? extends BaseViewHolder> viewHolderConstructor = getViewHolderClass().getConstructor(View.class);
        return viewHolderConstructor.newInstance(view);
    } catch (Exception e) {
        throw new FailedToCreateViewHolderException();
    }
}
```

Then we can have one method that pipes it all together used by `ViewCellAdapter` in `onCreateViewHolder()`:

```java
public TViewHolder createViewHolder(ViewGroup parent) {
    return createViewHolder(createView(parent));
}
```

If users just want to take over the entire `ViewHolder` generation process from start to end then they can just override `TViewHolder createViewHolder(ViewGroup parent)` and disregard the other two methods defined above.
